name: 🎵 Deploy Suno Prompt Generator

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    name: 🎉 Deploy para /suno-prompt/
    runs-on: ubuntu-latest
    
    steps:
      - name: 🚚 Baixar código
        uses: actions/checkout@v4
      
      - name: ✅ Verificar secrets configurados
        run: |
          echo "🔍 Verificando configuração de secrets..."
          if [ -z "${{ secrets.FTP_USERNAME }}" ]; then
            echo "❌ ERRO: Secret FTP_USERNAME não configurado!"
            echo "📝 Configure em: Settings > Secrets and variables > Actions"
            echo "   Nome: FTP_USERNAME"
            echo "   Valor: arquivos@linuxgo.com.br"
            exit 1
          fi
          
          if [ -z "${{ secrets.FTP_PASSWORD }}" ]; then
            echo "❌ ERRO: Secret FTP_PASSWORD não configurado!"
            exit 1
          fi
          
          echo "✅ Secrets configurados corretamente!"
          echo "👤 Usuário: ${{ secrets.FTP_USERNAME }}"
      
      - name: 🔍 Descobrir servidor correto
        id: find-server
        run: |
          servers=("linuxgo.com.br" "1gigahost.com.br" "ftp.1gigahost.com.br")
          
          for server in "${servers[@]}"; do
            echo "Testando: $server"
            if nslookup $server > /dev/null 2>&1; then
              echo "✅ DNS OK para: $server"
              echo "server=$server" >> $GITHUB_OUTPUT
              break
            else
              echo "❌ DNS falhou para: $server"
            fi
          done
          
          if [ -z "$(cat $GITHUB_OUTPUT)" ]; then
            echo "❌ Nenhum servidor FTP encontrado!"
            echo "🔧 Configure o secret FTP_SERVER manualmente"
            exit 1
          fi
      
      - name: 📂 Deploy via FTP
        if: steps.find-server.outputs.server
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ steps.find-server.outputs.server }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          protocol: ftp
          server-dir: /suno-prompt/
